# Generated by Django 5.1.5 on 2025-01-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0039_alter_accountingdimension_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='internal_partie',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='invoiceline',
            name='currency',
        ),
    ]
