# Generated by Django 5.1.5 on 2025-01-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0200_populate_mac_addresses'),
        ('netbox_contract', '0040_remove_contract_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingdimension',
            name='site',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='dcim.site'),
        ),
    ]
