# Generated by Django 5.1.5 on 2025-01-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0041_accountingdimension_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='accounting_code',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='netbox_contract.accountingdimension',
            ),
        ),
    ]
