# Generated by Django 5.1.5 on 2025-01-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_contract', '0042_contract_accounting_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='term_con',
            field=models.TextField(blank=True, null=True),
        ),
    ]
