# Generated by Django 5.1.5 on 2025-01-31 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0051_virtualcircuit_group_assignment'),
        ('extras', '0122_charfield_null_choices'),
        ('netbox_contract', '0043_contract_term_con'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='tags',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='netbox_cont_externa_6343fb_idx',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='external_partie_object_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='external_partie_object_type',
        ),
        migrations.AddField(
            model_name='contract',
            name='provider',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='circuits.provider'
            ),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['provider'], name='netbox_cont_provide_3da06f_idx'),
        ),
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
    ]
